### ISSUE TITLE
undefined method `first' for nil:NilClass when remote service unavailable

### ISSUE THREAD

**Issue by rilian** [denyago/remote_association#6] opened 2012-11-27 14:31 UTC
```
      undefined method `first' for nil:NilClass
```

**Comment by denyago** [comment] 2012-11-27 21:51
I can't reproduce it. Can you supply better example, where it fails?

Also, what do you mean under "remote service unavailable" ?

**Comment by denyago** [comment] 2012-12-11 13:45
Closing this issue. Feel free to re-open with failing code example.

**Closed as completed by denyago** 2012-12-11 13:45 UTC
